name: Api CI

on:
  push:
    branches:
    - develop
  pull_request:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - uses: RafikFarhad/push-to-gcr-github-action@v5-beta
      with:
        gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_ACCOUNT }}
        registry: gcr.io
        project_id: walls-immersive
        image_name: api-home
        image_tag: ${{ github.sha }}
        dockerfile: ./Dockerfile
        context: ./
      if: github.ref == 'refs/heads/develop'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCLOUD_SERVICE_ACCOUNT }}'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v1'
      with:
        service: ${{ github.event.pull_request.base.ref == 'main' && 'prod-home-api' || 'dev-home-api' }}
        image: gcr.io/walls-immersive/api-home:${{ env.COMMIT_SHA }}
        region: ${{ github.event.pull_request.base.ref == 'main' && 'europe-west1' || 'europe-west4' }}
      env:
        COMMIT_SHA: ${{ github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.sha || github.sha }}